INSERT INTO bookmarks (title, url, description, rating) 
VALUES ('Octinoxate and Avobenzone', 'sitemeter.com', 'Dickson', 4),
('SUNSCREEN, TITANIUM DIOXIDE, ZINC OXIDE', 'paypal.com', 'Linden', 2),
('Cetirizine HCl', 'globo.com', 'Nairy', 4),
('Triamterene and Hydrochlorothiazide', 'smugmug.com', 'Fairbeard', 1),
('Furosemide', 'omniture.com', 'Houlworth', 4),
('Wart Remover Liquid', 'bandcamp.com', 'Batchelder', 4),
('Calcium carbonate', 'flavors.me', null, 2),
('Octinoxate and Titanium Dioxide', 'state.tx.us', 'Churches', 2),
('Acetaminophen', 'ucsd.edu', null, 4),
('Mackerel', 'tuttocitta.it', null, 2),
('Cefuroxime Axetil', 'unblog.fr', 'Phelipeau', 5),
('rivastigmine', 'fema.gov', 'Trownson', 5),
('iopromide', 'dell.com', 'Goomes', 5),
('TITANIUM DIOXIDE and OCTINOXATE', 'yahoo.co.jp', null, 2),
('Omeprazole', 'chronoengine.com', null, 3),
('AVOBENZONE, OCTINOXATE, OCTISALATE', 'mail.ru', 'Burke', 4),
('Naltrexone Hydrochloride', 'oaic.gov.au', null, 4),
('clonidine hydrochloride', 'last.fm', null, 1),
('Metoprolol tartrate', 'themeforest.net', 'Bosdet', 2),
('Ropinirole Hydrochloride', 'sfgate.com', null, 2);